### ISSUE TITLE
Cloned repository does not contain external resources

### ISSUE THREAD

**Issue by KonstantinShemyak** [KonstantinShemyak/wheelbuildchart#17]
After edfc579, external libraries are not in the fresh clone, while we want them to be.

**Comment by plugz** [comment]
If your issue is with git-grep, instead of removing files from git, you should find a way to remove them form git-grep result.

See this for examples: https://stackoverflow.com/questions/10423143/how-to-exclude-certain-directories-files-from-git-grep-search

**Comment by KonstantinShemyak** [comment]
Closed by 9f32ffa8 by creating a Git submodule.
